### ISSUE TITLE
Python package numpy include is not general

### ISSUE THREAD

**Issue by aaron-gu** [databio/AIList#11]
https://github.com/databio/AIList/blob/2470d4fb96a8f062d09f5790db7d5ecb6ef101d0/src_py/setup.py#L26

The setup.py did not work after a fresh git clone. I looked into the issue and changed the last list element to my own local include at `/home/ag5ym/.local/lib/python2.7/site-packages/include`. Is it possible to change it so that it works for everyone without modification?

**Comment by nsheff** [comment]
@jf2016GH please don't hard-code private local folders into a `setup.py`

**Comment by jf2016GH** [comment]
Just realized that some guy made an AIList python wrapper earlier with the same name, so delete that package (ailist.python...gnu.so) and then install ours.
The setup.py does not use the local settings, it shouldn't matter and I just cleaned that.
