### ISSUE TITLE
Python package test example does not work

### ISSUE THREAD

**Issue by aaron-gu** [databio/AIList#12]
```
-bash-4.2$python ailist_test.py test1.bed test2.bed
Traceback (most recent call last):
  File "ailist_test.py", line 61, in <module>
    main(sys.argv)
  File "ailist_test.py", line 21, in main
    ail.addAll(argv[1])
AttributeError: 'ailist.ailist' object has no attribute 'addAll'
```

**Comment by jf2016GH** [comment]
try to clone to your local computer first. And you may need to install cython:
pip3 install cython

**Comment by aaron-gu** [comment]
Does it work on rivanna? That is where I am doing most of my work. Also, does this work with python2? I have installed cython in python2 but it is still giving me the same error.

**Comment by jf2016GH** [comment]
Did you try it with Python 3? That is what people normally use now.
Rivanna uses Python2. I didn't try it on python 2--which is not supported anymore.

**Comment by nsheff** [comment]
rivanna has python3 installed of course; just use python3. the databio module I think by default loads python3; if not, just load the anaconda module for python3 instead of python2.

**Comment by aaron-gu** [comment]
Works with python3! Sorry for the trouble
