### ISSUE TITLE
Python package on PyPI/bioconda?

### ISSUE THREAD

**Issue by endrebak** [databio/AIList#8]
To be able to easily use the AIlist in other projects it woud be neat if you could upload the package to pypi and bioconda. To upload it to pypi what you do is 

`python setup.py sdist` which is going to produce a file `dist/ailist-<version>` and then `twine upload dist/ailist-<version>`.

To upload it to bioconda you can do (after ailist is on pypi):

`conda skeleton pypi ailist --extra-specs cython`

This will create a `meta.yaml` which you can commit to the bioconda repo.

**Comment by nsheff** [comment]
I'm happy to put it on pypi -- we'll have to package it up first. This make take me a bit, though -- can you confirm that it does what you need it to do? I imagine you may require some other changes so I'm not sure putting in pypi immediately will be helpful yet.

**Comment by endrebak** [comment]
I have created two issues which I think you would need to address to match the speed and usability of the NCLS *in Python* :) . I'm sure your AIList is faster, but to get equal speed and convenience in Python it should ideally work with the Python data science stack and its data-structures :)

**Comment by nsheff** [comment]
Thanks a bunch, this looks like a great start. we'll work on these updates.

**Comment by jf2016GH** [comment]
I am not sure how fast NCLS in python is. Can you run it with the test datasets provided in this repo?
The included AIList-python takes more time on data-loading than search. You are welcome if you want to build a python wrapper of AIList in the way you built NCLS -python. The source files in folder src_py are a little different from that in src.

**Comment by endrebak** [comment]
Thanks, I see myself doing it sometime in the future as an upgrade/boost to PyRanges for a potential second paper :) I will let you guys reach a stable version before I do anything.

**Comment by jf2016GH** [comment]
Thanks. I am in the middle of some other projects now and I'll come back to this later.

**Comment by endrebak** [comment]
https://github.com/kylessmith/ailist
