### ISSUE TITLE
Add index field to AIlist?

### ISSUE THREAD

**Issue by endrebak** [databio/AIList#9]
If you could add an index or id field (int64) to the ailist that would be helpful.

This id can be used to store additional metadata about each interval in a map or rows of a dataframe. Currently if you search the AIlist you get interval locations in return, but without an ID, fetching the information about the intervals you found is not easy. 

I think this is going to be a major issue for many - you often do not just want to know the positions of what you overlapped, but also metadata about the intervals.

**Comment by jf2016GH** [comment]
AIList uses two IDs to access the 'database' interval, first the gid for the contig then the id for the interval in that contig.

**Comment by endrebak** [comment]
But those ids are hidden from the user. If I do a query in the tree with `tree.search(54, 66)` I would like to get more than just the overlapping intervals, e.g. (0, 100) and (20, 55). I would like an identifier too so that I can look up additional metadata about those intervals.

**Comment by jf2016GH** [comment]
Use the in-line function get_value(...) to retrieve the info. You can modify the AIList c code in src_py folder to record the value you like.

**Comment by jf2016GH** [comment]
Add two c functions to build and search for python, rewrite the wrapper. The python code is now very close to c code.

**Comment by endrebak** [comment]
Cool! I really appreciate your work and invention. The simplicity of the AIList makes it a prime candidate for multithreading with openMP (easy in Cython), but I do not know if it will be worth it. 8 seconds on 1e7 intervals is extremely good already 👍
